build v1.0
dawilles/KnightWars pull request #1
Opened 2023-05-20 02:01 UTC by dawilles

2023-05-20 14:34 UTC, zem-aleks requested changes

2023-05-20 14:34 UTC, zem-aleks commented on heroes.js
> +const Heroes = (() => {
Please, NEVER wrap classes into module. Class is a type

2023-05-20 14:34 UTC, zem-aleks commented on render.js
> +const Render = (() => {
It's no a class, should start from small letter

2023-05-20 14:34 UTC, zem-aleks commented on render.js
> +const selectors = {
It's a global const. Sometimes it's okay to left it as it's now, but to clearly explain idea it's better to make SELECTORS and attributes also with big letters: KNIGHT: { HEALTH: "" }

2023-05-20 14:34 UTC, zem-aleks commented on ai.js
> +const IA = (() => {
not big letters and it's not clear what this means. Maybe you meant ia as artificial intelligence? Anyway, it's better to explain that it's IA belong to heroes or game or some comments :)

2023-05-20 14:34 UTC, zem-aleks commented on game.js
> +		let playerDamage = player[action]();
Wy do you use let instead of const?

2023-05-20 14:34 UTC, zem-aleks commented on game.js
> +			choice === "knight"
It's better to make a switch/case by choice

2023-05-20 14:34 UTC, zem-aleks commented on game.js
> +const Game = (() => {
Heroes are created with classes. It's better to continue style of code and also make it as a class. Only classes start with big letter. Module is a variable, not a class!!!

2023-05-20 14:34 UTC, zem-aleks commented on game.js
> +		IA.setOpponent(player);
IA is a game dependency. Must provided as constructor parameter or as a function parameter. If ia.js file is not connected or you will decide to use another ia implementation, game either will be broken or must be refactored

2023-05-20 14:34 UTC, zem-aleks commented on game.js
> +		Render.updateUI(player, computer, playerChoice);
Game only should wok with a game logic and has no options to call renders. You can create some events inside your game and app can listen these events and do some rendering, but no rendering from the game!

2023-05-20 14:34 UTC, zem-aleks commented on ai.js
> +const IA = (() => {
And it's better to make it as class, because it's abstraction that can be extended later

2023-05-25 16:36 UTC, zem-aleks requested changes

2023-05-25 16:36 UTC, zem-aleks commented on app.js
> +		document
1 event listener for 2 controls

2023-05-25 16:36 UTC, zem-aleks commented on gameAi.js
> +	getMove(opponent) {
could be game as a main parameter. Based on game state you can make all decisions

2023-05-29 15:47 UTC, zem-aleks requested changes

2023-05-29 15:47 UTC, zem-aleks commented on app.js
> +		const createGame = (isKnight) => {
move this function outside of init function

2023-05-29 15:47 UTC, zem-aleks commented on app.js
> +		setupEventListener(".form-mag", "submit", (event) => {
code duplication! DRY :)

2023-05-29 15:47 UTC, zem-aleks commented on gameAi.js
> +		} else if (opponent.mana < 20 || opponent.energy < 20) {
don't make "else if", if you have a return in the previous statement. It's enough to make new "if". 
Such statements are easier for understanding

2023-05-29 15:47 UTC, zem-aleks commented on gameModule.js
> +			events: {
Please move it to DEFAULT_EVENTS constant

and this function can be used: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

2023-05-30 19:44 UTC, dawilles commented on gameAi.js
> +	getMove(opponent) {
done

2023-05-30 20:00 UTC, dawilles commented on gameAi.js
> +		} else if (opponent.mana < 20 || opponent.energy < 20) {
done

2023-05-30 20:00 UTC, dawilles commented on app.js
> +		setupEventListener(".form-mag", "submit", (event) => {
done

2023-05-30 20:00 UTC, dawilles commented on gameModule.js
> +			events: {
done

2023-05-30 20:00 UTC, dawilles commented on app.js
> +		const createGame = (isKnight) => {
done

2023-09-03 23:04 UTC, merged